# Generated by Django 3.0.1 on 2019-12-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0001_initial"),
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookmarks", models.ManyToManyField(to="bookmarks.Bookmark")),
                ("tags", models.ManyToManyField(to="tags.TaggedItem")),
            ],
        ),
    ]
