# Generated by Django 2.1.2 on 2018-10-03 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='PodcastItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('synopsis', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'podcast_item',
            },
        ),
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='podcastitem',
            name='podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='podcast.Podcast'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='podcast', to='podcast.Host'),
        ),
    ]
