# Generated by Django 3.0.1 on 2019-12-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_hash", models.CharField(max_length=32, null=True)),
                ("usr_id", models.CharField(max_length=32, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.RenameModel(old_name="Post", new_name="PostRelation",),
    ]
